### ISSUE TITLE
UN-InstallMilitaryToolsForArcMap.bat - Indicates failed - seems to need quotes on paths with spaces

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-for-arcgis#28]
@csmoore 
UN-InstallMilitaryToolsForArcMap.bat - Indicates "Uninstallation failed" - seems to need quotes on paths with spaces

![image](https://cloud.githubusercontent.com/assets/6842145/16692988/28587072-4501-11e6-8f08-ef64c6bc73f7.png)

**Comment by csmoore** [comment]
Sorry about that - looks like this never actually worked on ArcMap & you are the first one to try/report

https://github.com/Esri/military-tools-for-arcgis/pull/29 - @pshowalter please verify

**Comment by pshowalter** [comment]
@csmoore @jmccausland @dhagens 

It seems that the AddIns are installed in
C:\Users\XXXX\Documents\ArcGIS\AddIns\Desktop10.3.  

ArcMap 10.4.1 will find them and use them, but the UninstallMilitaryToolsForArcMap.bat and ESRIRegAddIn.exe is looking for the "Add In ID" folder in the 
C:\Users\XXXX\Documents\ArcGIS\AddIns\Desktop10.4 folder.  

If the AddIn's arc copied from \Desktop10.3 to \Desktop10.4 folder the Uninstall script does not indicate that it failed.

I also see in the source code that  that carries through to the Config.xml in the AddInf is:
<Target name="Desktop" version="10.3" />

**Comment by csmoore** [comment]
@pshowalter - I'm not sure I quite understand the issue reported. Is the issue that the ArcMap Addins are installed to `Documents\ArcGIS\AddIns\Desktop10.3` regardless of the ArcGIS version installed and the uninstall doesn't uninstall them on 10.4? 

If this is this a new/different issue [with the Install Script](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/InstallMilitaryToolsForArcMap.bat) or [DAML](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/Config.esriaddinx#L11) rather than the [uninstall script](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/UN-InstallMilitaryToolsForArcMap.bat) ? You may want to still close this issue and open a new one (just so this one gets resolved)

**Comment by pshowalter** [comment]
Exactly.  The Military Workflows Addins  are placed in the \10.3 folder, but ESRIRegAddIn.exe used in batch script looks in the \10.4 folder, and then indicates it failed.

**Comment by csmoore** [comment]
That is odd behavior - I would say that sounds like a bug in ESRIRegAddIn.exe 

But does sound like we can fix(or workaround) by changing to 10.4 in the [DAML](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/Config.esriaddinx#L11) - is the expected version for this 10.4 now or is it still targeting 10.3.1 (that's what it says in the [readme](https://github.com/Esri/military-tools-for-arcgis#arcgis-for-desktop-users) )?

**Comment by pshowalter** [comment]
@topowright 
My understanding is that release is targeting 10.4.1 and 1.3, which would mean that the [readme](https://github.com/Esri/military-tools-for-arcgis#arcgis-for-desktop-users) and some other documentation would needs updating, as well as and  [DAML](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/Config.esriaddinx#L11)
that references previous version.

**Comment by lfunkhouser** [comment]
Closing. No longer valid. The tools will installed with a single add-in.
