### ISSUE TITLE
Text not displaying for bearing and distance units. - Pro 1.2

### ISSUE THREAD

**Issue by abrowning80** [Esri/military-tools-for-arcgis#56]
## Expected Behavior
Display of text in Table to line of bearing geoprocessing tool for Bearing units and Distance Units

## Current Behavior
Both of these are showing the code ie 9001 for distance units instead of meters.  Meaning that the user is unable to know what they are setting.

## Steps to Reproduce (for bugs)
1.  Open table to line of bearing geoprocessing tool
2.  Try to set bearing and distance units.
3.
4.

## Context

##Your Environment

* Version used: ArcPro 1.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): Windows 8 desktop
* Link to your project:

**Comment by jmhauck** [comment]
@kgonzago @nfeuerstein I am not seeing this issue. I am testing at Pro 1.4 (7119) a build from last week. Should I check against the currently released version also? If I am following correctly I was expecting to see the value of '9001' for example rather than the value 'METERS'.

![image](https://cloud.githubusercontent.com/assets/2170893/20937691/454a7ce6-bba5-11e6-80aa-9a272344b8d5.png)

**Comment by jmhauck** [comment]
Out of curiosity I checked on 1.3.1 and don't see there either.

**Comment by kgonzago** [comment]
could not repro. closing it.
